title: Genderkit
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://genderkit.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: /genderkit
twitter_username: jekyllrb
github_username:  genderkit

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - "old/*"
  - vendor # Gem install location under travis
  - scripts
  - .travis.yml

collections:
  articles:
    output: true
  categories:
    output: true

defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: page
      weighting: 999
      permalink: /article/:name/
  - scope:
      path: ""
      type: categories
    values:
      layout: category
      permalink: /category/:name/

stylus:
  compress: true
